### ISSUE TITLE
ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by rafhtl** [Razzeee/script.module.arrow#3]
Kodi 19 rpi4
I have this problem since yesterday
script.module.arrow/lib/arrow/locales.py", line 19, in <module>
                                                       from typing_extensions import Literal
                                                   ModuleNotFoundError: No module named 'typing_extensions'

can you help me?
thank you

**Comment by razzeee** [comment]
When does this happen for you? Just on the home screen?

**Comment by rafhtl** [comment]
Yes as soon as I start kodi
thank you

**Comment by razzeee** [comment]
Can you update your system python?

**Comment by rafhtl** [comment]
you mean a  sudo apt-get full-upgrade?

**Comment by razzeee** [comment]
If that's what it needs, I guess that's the big hammer

**Comment by rafhtl** [comment]
my versions
Python 2.7.16
Python 3.7.3

thank you

**Comment by rafhtl** [comment]
I can you tell you that this happened AFTER I recently upgraded python (2 days ago)

**Comment by razzeee** [comment]
Best wouldpprobably be to get you on something like python > 3.8

**Comment by rafhtl** [comment]
But why is this happening now
I mean shouldnt the addon be compatible with kodi and the system?
thank you

**Comment by razzeee** [comment]
https://github.com/Razzeee/script.module.arrow/blob/main/lib/arrow/locales.py#L19

Latest arrow version seems to have started using https://pypi.org/project/typing-extensions/ if your below python 3.8

**Comment by razzeee** [comment]
Installing https://github.com/Razzeee/script.module.typing_extensions might help?

**Comment by rafhtl** [comment]
ill try now
thanks

**Comment by rafhtl** [comment]
still giving me error

File "/home/xbian/.kodi/addons/script.embuary.info/service.py", line 8, in <module>
                                                       from resources.lib.helper import *
                                                     File "/home/xbian/.kodi/addons/script.embuary.info/resources/lib/helper.py", line 15, in <module>
                                                       import arrow
                                                     File "/home/xbian/.kodi/addons/script.module.arrow/lib/arrow/__init__.py", line 2, in <module>
                                                       from .api import get, now, utcnow
                                                     File "/home/xbian/.kodi/addons/script.module.arrow/lib/arrow/api.py", line 12, in <module>
                                                       from arrow.arrow import TZ_EXPR, Arrow
                                                     File "/home/xbian/.kodi/addons/script.module.arrow/lib/arrow/arrow.py", line 34, in <module>
                                                       from arrow import formatter, locales, parser, util
                                                     File "/home/xbian/.kodi/addons/script.module.arrow/lib/arrow/formatter.py", line 8, in <module>
                                                       from arrow import locales
                                                     File "/home/xbian/.kodi/addons/script.module.arrow/lib/arrow/locales.py", line 19, in <module>
                                                       from typing_extensions import Literal
                                                   ModuleNotFoundError: No module named 'typing_extensions'
                                                   -->End of Python script error report<--

maybe has to be included as dependency?

thank you

**Comment by razzeee** [comment]
You can try to add that to your `addon.xml` https://github.com/Razzeee/script.module.arrow/blob/main/addon.xml#L8 but I'm not sure if that's needed. Usually it takes care of you downloading it.

**Comment by rafhtl** [comment]
tried but doesn't work

**Comment by razzeee** [comment]
I was able to fake it failing to import and fix it using the latest version of https://github.com/Razzeee/script.module.typing_extensions

**Comment by rafhtl** [comment]
Thank you
that does solve the problem!
raf
